# Generated by Django 2.2.7 on 2019-11-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sandbox_instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleAllocationStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instances.Stage')),
                ('repo_url', models.TextField()),
                ('rev', models.TextField()),
            ],
            bases=('sandbox_instances.stage',),
        ),
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnsibleOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='sandbox_ansible_runs.AnsibleAllocationStage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
