# Generated by Django 2.2.7 on 2019-11-14 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instances', '0001_initial'),
        ('sandbox_ansible_runs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansibleallocationstage',
            name='stage_ptr',
        ),
        migrations.AddField(
            model_name='ansibleallocationstage',
            name='allocationstage_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instances.AllocationStage'),
            preserve_default=False,
        ),
    ]
