# Generated by Django 2.2.7 on 2019-11-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instances', '0002_cleanupstage_stackcleanupstage'),
        ('sandbox_ansible_runs', '0002_auto_20191114_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleCleanupStage',
            fields=[
                ('cleanupstage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instances.CleanupStage')),
            ],
            bases=('sandbox_instances.cleanupstage',),
        ),
    ]
