# Generated by Django 2.2.7 on 2019-11-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_ansible_runs', '0003_ansiblecleanupstage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockercontainer',
            name='id',
        ),
        migrations.AddField(
            model_name='ansiblecleanupstage',
            name='allocation_stage',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_stage', to='sandbox_ansible_runs.AnsibleAllocationStage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='stage',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='container', serialize=False, to='sandbox_ansible_runs.AnsibleAllocationStage'),
            preserve_default=False,
        ),
    ]
