# Generated by Django 2.2.7 on 2019-11-05 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sandbox_definitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_size', models.IntegerField()),
                ('private_management_key', models.TextField()),
                ('public_management_key', models.TextField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sandbox_definitions.Definition')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=None, null=True)),
                ('end', models.DateTimeField(default=None, null=True)),
                ('failed', models.BooleanField(default=False)),
                ('error_message', models.TextField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SystemProcesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instances.Stage')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('sandbox_instances.stage',),
        ),
        migrations.CreateModel(
            name='SandboxAllocationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_units', to='sandbox_instances.Pool')),
            ],
        ),
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_user_key', models.TextField()),
                ('public_user_key', models.TextField()),
                ('allocation_unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sandbox', to='sandbox_instances.SandboxAllocationUnit')),
                ('lock', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sandbox', to='sandbox_instances.Lock')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CleanupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('allocation_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanuprequests', to='sandbox_instances.SandboxAllocationUnit')),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('allocation_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocationrequests', to='sandbox_instances.SandboxAllocationUnit')),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StackAllocationStage',
            fields=[
                ('allocationstage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instances.AllocationStage')),
                ('status', models.CharField(max_length=30, null=True)),
                ('status_reason', models.TextField(null=True)),
            ],
            bases=('sandbox_instances.allocationstage',),
        ),
        migrations.AddField(
            model_name='allocationstage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sandbox_instances.AllocationRequest'),
        ),
    ]
