# Generated by Django 2.2.9 on 2020-01-06 13:29

from django.db import migrations, models
import kypo.sandbox_common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='uuid',
            field=models.TextField(default=kypo.sandbox_common.utils.get_simple_uuid),
        ),
    ]
