# Generated by Django 2.2.7 on 2019-11-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instances.Stage')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sandbox_instances.CleanupRequest')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('sandbox_instances.stage',),
        ),
        migrations.CreateModel(
            name='StackCleanupStage',
            fields=[
                ('cleanupstage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instances.CleanupStage')),
                ('status', models.CharField(max_length=30, null=True)),
                ('status_reason', models.TextField(null=True)),
            ],
            bases=('sandbox_instances.cleanupstage',),
        ),
    ]
