# Generated by Django 2.2.7 on 2019-11-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instances', '0002_cleanupstage_stackcleanupstage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackcleanupstage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stackcleanupstage',
            name='status_reason',
        ),
        migrations.AddField(
            model_name='stackcleanupstage',
            name='allocation_stage',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_stage', to='sandbox_instances.StackAllocationStage'),
            preserve_default=False,
        ),
    ]
