# Generated by Django 2.2.9 on 2020-01-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instances', '0002_pool_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandbox',
            name='lock',
        ),
        migrations.AddField(
            model_name='lock',
            name='sandbox',
            field=models.OneToOneField(default=16, on_delete=django.db.models.deletion.PROTECT, related_name='lock', to='sandbox_instances.Sandbox'),
            preserve_default=False,
        ),
    ]
