# Generated by Django 2.2.7 on 2019-11-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instances', '0003_auto_20191114_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatstack',
            name='id',
        ),
        migrations.AddField(
            model_name='heatstack',
            name='stage',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='heatstack', serialize=False, to='sandbox_instances.StackAllocationStage'),
            preserve_default=False,
        ),
    ]
