# Name of the microservice.
#microservice_name: kypo-sandbox-service

# A prefix of the stack in the cloud with maximum 8 characters.
#stack_name_prefix: default0

# A boolean that turns on/off debug mode.
# SECURITY WARNING: don't run with debug turned on in production!
debug: True

# A list of strings representing the host/domain names that this Django site can serve.
#allowed_hosts: []

# If True, the whitelist will not be used and all origins will be accepted.
#cors_origin_allow_all: True

# A list of origins that are authorized to make cross-site HTTP requests.
#cors_origin_whitelist: []

authentication:
    # Whether the REST API authentication is on.
    # If set to False, other authentication variables are not used.
    #authenticated_rest_api: False

    # List of OIDC provider host/domain names that are allowed.
    allowed_oidc_providers: []

    # User and Group roles registration endpoint URL.
    roles_registration_url: ""

    # User and Group roles acquisition endpoint URL.
    roles_acquisition_url: ""

application_configuration:
    # The IP address of the KYPO head server.
    #kypo_head_ip: 0.0.0.0

    # The URL of OpenStack Identity service API.
    os_auth_url: ""

    # The ID of application credentials to authenticate at OpenStack cloud platform.
    os_application_credential_id: ""

    # The secret string of APPLICATION_CREDENTIAL_ID.
    os_application_credential_secret: ""

    # The OpenStack console type. One of: novnc, xvpvnc, spice-html5, rdp-html5, serial, webmks.
    #os_console_type: spice-html5

    # The path to project log file.
    #log_file: kypo-sandbox-service.log

    # The level of log verbosity. One of: NOTSET, DEBUG, INFO, WARNING, ERROR, FATAL, CRITICAL.
    #log_level: INFO

    # The type of Git repositories. One of: INTERNAL, GITLAB.
    #git_type: INTERNAL

    # Git server hostname or IP.
    #git_server: gitlab.com

    # The address of Git REST server with protocol (optionally port)
    #git_rest_server: https://gitlab.com/

    # The name of user used for communication with Git repository.
    #git_user: git

    # The SSH private key that kypo2-django-openstack uses to communicate with Git repository.
    #git_private_key: ~/.ssh/git_rsa_key

    # The access token for Gitlab API
    git_access_token: ""

    # The URL of Ansible networking Git repository.
    ansible_networking_url: ""

    # The rev of Ansible networking Git repository.
    #ansible_networking_rev: master

    # The pattern to be replaced in image names of sandbox definitions.
    #image_naming_strategy:
    #    pattern: ^
    #    replace: ''

    # The mapping of flavor names to be replaced in sandbox definition.
    #flavor_mapping: {}

    # The object that represents SSH Host entry (see man page of ssh_config).
    proxy_jump_to_man:
        Host: ""
        User: ""
        IdentityFile: ""

    # Timeout of sandbox (stack) creation in cloud in seconds.
    #sandbox_build_timeout: 7200

    # Timeout of sandbox (stack) deletion in cloud in seconds.
    #sandbox_delete_timeout : 3600

    # Timeout for Ansible.
    #sandbox_ansible_timeout: 7200

    # The path to local temporary directory where KYPO will prepare Docker volumes.
    #ansible_docker_volumes: /tmp/kypo

    # The name of the Docker image that is able to run Ansible playbook.
    #ansible_docker_image: csirtmu/kypo-ansible-runner

    # The name of the Docker network that the Runner will use.
    #ansible_docker_network: bridge

    # The address of kypo-answers-storage REST API
    #answers_storage_api: http://answers-storage:8087/kypo-answers-storage/api/v1

    # A path to directory of CA certificates or file of CA certificates, i.e. CA bundle.
    # Use in case of self-signed certificates in related services.
    #ssl_ca_certificate_verify: ""

    sandbox_configuration:
        # The name or ID of network in OpenStack where all sandboxes will be deployed.
        #base_network: base_network

        # The name of the image in OpenStack that will be used for management nodes (MAN, UAN, BR).
        extra_nodes_image: ""

        # The name of user in MNG_IMAGE virtual machine.
        extra_nodes_user: ""

        # The name of the flavor in OpenStack that will be used for management nodes.
        extra_nodes_flavor: ""

        # The cidr notation of network between MAN and every other node in sandbox.
        #sb_man_cidr: 192.168.128.0/17

        # The cidr notation of network between UAN and MAN node.
        #sb_uan_cidr: 192.168.0.0/28

        # The cidr notation of network between BR and MAN node.
        #sb_br_cidr: 192.168.0.16/28

        # The list of IP addresses to custom DNS servers.
        #dns_name_servers: []

