[tox]
parallel_show_output = True
envlist = pre-commit, pylint, bandit, audit, pytest

[testenv]
ignore_outcome = True
deps =
    pytest
    pytest-mock
    pytest-structlog
setenv = DJANGO_SETTINGS_MODULE=crczp.sandbox_service_project.tests.settings
passenv = PYPI_DOWNLOAD_URL
commands = pytest -m "not integration" --basetemp={envtmpdir} {posargs} -s
           python manage.py check


# pre-commit covers ruff lint, ruff format, mypy
[testenv:pre-commit]
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure

[testenv:pylint]
deps = pylint
commands = pylint crczp tests --output-format=colorized

[testenv:bandit]
deps = bandit
commands = bandit -r crczp

[testenv:audit]
deps = pip-audit
commands = pip-audit --progress-spinner=off

[testenv:pytest]
DJANGO_SETTINGS_MODULE = crczp.sandbox_service_project.tests.settings
testpaths = crczp/sandbox_ansible_app/tests
            crczp/sandbox_common_lib/tests
            crczp/sandbox_definition_app/tests
            crczp/sandbox_instance_app/tests
            crczp/sandbox_service_project/tests
deps =
    djangorestframework<3.15.0
    ruamel.yaml<0.18.0
    pytest
    pytest-django
    pytest-mock
    pytest-structlog
commands = pytest
markers = integration
