[tox]
envlist = pre-commit, pylint, bandit, audit, pytest

[testenv]
setenv = DJANGO_SETTINGS_MODULE=crczp.sandbox_service_project.tests.settings
passenv = PYPI_DOWNLOAD_URL

[testenv:pylint]
deps =
    pylint
    pylint-django
    pytest
    django~=5.0
    djangorestframework
setenv = DJANGO_SETTINGS_MODULE=crczp.sandbox_service_project.settings
commands = pylint crczp --load-plugins=pylint_django --output-format=colorized --fail-under=9.5

[testenv:bandit]
deps = bandit
commands = bandit -r crczp -c pyproject.toml

[testenv:audit]
deps = pip-audit
commands = pip-audit --progress-spinner=off .

[testenv:pytest]
deps =
    pytest
    pytest-django
    pytest-mock
    pytest-structlog
    fakeredis[lua]
testpaths = crczp/sandbox_ansible_app/tests
            crczp/sandbox_common_lib/tests
            crczp/sandbox_definition_app/tests
            crczp/sandbox_instance_app/tests
            crczp/sandbox_service_project/tests
commands =
    pytest -m "not integration" {posargs}
    pytest -m "integration" {posargs}
    python manage.py check

# pre-commit covers ruff lint, ruff format, mypy
[testenv:pre-commit]
deps = pre-commit
commands =
    pre-commit run --all-files --show-diff-on-failure
