# Generated by Django 2.2.9 on 2020-01-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sandbox_instance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleAllocationStage',
            fields=[
                ('allocationstage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instance_app.AllocationStage')),
                ('repo_url', models.TextField()),
                ('rev', models.TextField()),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('sandbox_instance_app.allocationstage',),
        ),
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='container', serialize=False, to='sandbox_ansible_app.AnsibleAllocationStage')),
                ('container_id', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnsibleOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='sandbox_ansible_app.AnsibleAllocationStage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnsibleCleanupStage',
            fields=[
                ('cleanupstage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instance_app.CleanupStage')),
                ('allocation_stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_stage', to='sandbox_ansible_app.AnsibleAllocationStage')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('sandbox_instance_app.cleanupstage',),
        ),
    ]
