# Generated by Django 2.2.10 on 2020-02-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_ansible_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansiblecleanupstage',
            name='allocation_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_stages', to='sandbox_ansible_app.AnsibleAllocationStage'),
        ),
    ]
