# Generated by Django 2.2.11 on 2020-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_ansible_app', '0002_auto_20200228_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansibleallocationstage',
            name='repo_url',
            field=models.TextField(help_text='URL of the Ansible repository.'),
        ),
        migrations.AlterField(
            model_name='ansibleallocationstage',
            name='rev',
            field=models.TextField(help_text='Revision of the Ansible repository.'),
        ),
    ]
