# Generated by Django 2.2.20 on 2021-05-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0002_pool_management_certificate'),
        ('sandbox_ansible_app', '0003_dockercontainercleanup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnsibleOutput',
            new_name='AllocationAnsibleOutput',
        ),
        migrations.CreateModel(
            name='CleanupAnsibleOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('cleanup_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='sandbox_instance_app.CleanupStage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
