# Generated by Django 2.2.24 on 2021-09-20 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sandbox_definition_app', '0002_auto_20200409_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='created_by',
            field=models.ForeignKey(help_text='The user that created this definition.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
