# Generated by Django 2.2.9 on 2020-01-16 14:48

import django.utils.timezone
from django.db import migrations, models

import kypo.sandbox_common_lib.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sandbox_definition_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=None, null=True)),
                ('end', models.DateTimeField(default=None, null=True)),
                ('failed', models.BooleanField(default=False)),
                ('error_message', models.TextField(null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sandbox_instance_app.AllocationRequest')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleanupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleanupStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=None, null=True)),
                ('end', models.DateTimeField(default=None, null=True)),
                ('failed', models.BooleanField(default=False)),
                ('error_message', models.TextField(null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sandbox_instance_app.CleanupRequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_size', models.IntegerField()),
                ('private_management_key', models.TextField()),
                ('public_management_key', models.TextField()),
                ('uuid', models.TextField(default=kypo.sandbox_common_lib.utils.get_simple_uuid)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sandbox_definition_app.Definition')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SystemProcesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StackAllocationStage',
            fields=[
                ('allocationstage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instance_app.AllocationStage')),
                ('status', models.CharField(max_length=30, null=True)),
                ('status_reason', models.TextField(null=True)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('sandbox_instance_app.allocationstage',),
        ),
        migrations.CreateModel(
            name='SandboxAllocationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_units', to='sandbox_instance_app.Pool')),
            ],
        ),
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_user_key', models.TextField()),
                ('public_user_key', models.TextField()),
                ('allocation_unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sandbox', to='sandbox_instance_app.SandboxAllocationUnit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandbox', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lock', to='sandbox_instance_app.Sandbox')),
            ],
        ),
        migrations.AddField(
            model_name='cleanuprequest',
            name='allocation_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_requests', to='sandbox_instance_app.SandboxAllocationUnit'),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='allocation_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_request', to='sandbox_instance_app.SandboxAllocationUnit'),
        ),
        migrations.CreateModel(
            name='HeatStack',
            fields=[
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='heatstack', serialize=False, to='sandbox_instance_app.StackAllocationStage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StackCleanupStage',
            fields=[
                ('cleanupstage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instance_app.CleanupStage')),
                ('allocation_stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_stage', to='sandbox_instance_app.StackAllocationStage')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('sandbox_instance_app.cleanupstage',),
        ),
    ]
