# Generated by Django 2.2.13 on 2020-06-19 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kypo.sandbox_common_lib.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sandbox_definition_app', '0002_auto_20200409_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=None, help_text='Timestamp indicating when the stage execution started.', null=True)),
                ('end', models.DateTimeField(default=None, help_text='Timestamp indicating when the stage execution ended.', null=True)),
                ('failed', models.BooleanField(default=False, help_text='Indicates whether the stage execution failed.')),
                ('error_message', models.TextField(default=None, help_text='Error message describing the potential error.', null=True)),
                ('finished', models.BooleanField(default=False, help_text='Indicates whether the stage execution has finished.')),
                ('allocation_request_fk_many', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sandbox_instance_app.AllocationRequest')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleanupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleanupStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=None, help_text='Timestamp indicating when the stage execution started.', null=True)),
                ('end', models.DateTimeField(default=None, help_text='Timestamp indicating when the stage execution ended.', null=True)),
                ('failed', models.BooleanField(default=False, help_text='Indicates whether the stage execution failed.')),
                ('error_message', models.TextField(default=None, help_text='Error message describing the potential error.', null=True)),
                ('finished', models.BooleanField(default=False, help_text='Indicates whether the stage execution has finished.')),
                ('cleanup_request_fk_many', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sandbox_instance_app.CleanupRequest')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_size', models.IntegerField(help_text='Maximum amount of Allocation Units associated with this pool.')),
                ('private_management_key', models.TextField(help_text='Private key for management access.')),
                ('public_management_key', models.TextField(help_text='Public key for management access.')),
                ('uuid', models.TextField(default=kypo.sandbox_common_lib.utils.get_simple_uuid)),
                ('rev', models.TextField(help_text='Definition revision used for sandboxes.')),
                ('rev_sha', models.TextField(help_text='SHA of the Definition revision.')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sandbox_definition_app.Definition')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('id', models.PositiveIntegerField(default=-1024, primary_key=True, serialize=False)),
                ('private_user_key', models.TextField(help_text='Private key for user access.')),
                ('public_user_key', models.TextField(help_text='Public key for management access.')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AllocationRQJob',
            fields=[
                ('job_id', models.TextField()),
                ('allocation_stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rq_job', serialize=False, to='sandbox_instance_app.AllocationStage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleanupRQJob',
            fields=[
                ('job_id', models.TextField()),
                ('cleanup_stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rq_job', serialize=False, to='sandbox_instance_app.CleanupStage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.TextField()),
                ('allocation_stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sandbox_instance_app.AllocationStage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SandboxLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandbox', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lock', to='sandbox_instance_app.Sandbox')),
            ],
        ),
        migrations.CreateModel(
            name='SandboxAllocationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_units', to='sandbox_instance_app.Pool')),
            ],
        ),
        migrations.AddField(
            model_name='sandbox',
            name='allocation_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sandbox', to='sandbox_instance_app.SandboxAllocationUnit'),
        ),
        migrations.CreateModel(
            name='PoolLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lock', to='sandbox_instance_app.Pool')),
            ],
        ),
        migrations.CreateModel(
            name='HeatStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_id', models.TextField()),
                ('allocation_stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sandbox_instance_app.AllocationStage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cleanuprequest',
            name='allocation_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_request', to='sandbox_instance_app.SandboxAllocationUnit'),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='allocation_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_request', to='sandbox_instance_app.SandboxAllocationUnit'),
        ),
        migrations.CreateModel(
            name='StackCleanupStage',
            fields=[
                ('cleanupstage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instance_app.CleanupStage')),
                ('cleanup_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sandbox_instance_app.CleanupRequest')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('sandbox_instance_app.cleanupstage',),
        ),
        migrations.CreateModel(
            name='StackAllocationStage',
            fields=[
                ('allocationstage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox_instance_app.AllocationStage')),
                ('status', models.CharField(help_text='Stack status', max_length=30, null=True)),
                ('status_reason', models.TextField(help_text='Stack status reason', null=True)),
                ('allocation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sandbox_instance_app.AllocationRequest')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('sandbox_instance_app.allocationstage',),
        ),
    ]
