# Generated by Django 2.2.10 on 2020-02-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatstack',
            name='stack_id',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
