# Generated by Django 2.2.10 on 2020-03-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemProcess',
            fields=[
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='process', serialize=False, to='sandbox_instance_app.AllocationStage')),
                ('process_id', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SystemProcesses',
        ),
        migrations.AddField(
            model_name='heatstack',
            name='stack_id',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stackcleanupstage',
            name='allocation_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_stages', to='sandbox_instance_app.StackAllocationStage'),
        ),
    ]
