# Generated by Django 2.2.18 on 2021-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='management_certificate',
            field=models.TextField(default='certificate', help_text='Certificate for windows management access.'),
            preserve_default=False,
        ),
    ]
