# Generated by Django 2.2.10 on 2020-02-28 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0002_heatstack_stack_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemProcess',
            fields=[
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='process', serialize=False, to='sandbox_instance_app.StackAllocationStage')),
                ('process_id', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SystemProcesses',
        ),
        migrations.AlterField(
            model_name='heatstack',
            name='stack_id',
            field=models.TextField(),
        ),
    ]
