# Generated by Django 2.2.11 on 2020-03-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0002_auto_20200304_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='rev',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
