# Generated by Django 2.2.10 on 2020-03-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0002_auto_20200304_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lock',
            new_name='SandboxLock',
        ),
        migrations.CreateModel(
            name='PoolLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lock', to='sandbox_instance_app.Pool')),
            ],
        ),
    ]
