# Generated by Django 2.2.11 on 2020-03-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0003_auto_20200305_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='rev',
            field=models.TextField(default='master'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='rev_sha',
            field=models.TextField(default='master'),
            preserve_default=False,
        ),
    ]
