# Generated by Django 2.2.11 on 2020-03-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0003_pool_rev'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='rev_sha',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
