# Generated by Django 2.2.10 on 2020-02-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0003_auto_20200228_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprocess',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='process', serialize=False, to='sandbox_instance_app.AllocationStage'),
        ),
    ]
