# Generated by Django 2.2.11 on 2020-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0004_auto_20200310_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationstage',
            name='type',
            field=models.CharField(choices=[('openstack', 'openstack'), ('ansible', 'ansible')], default='openstack', help_text='Type of the stage', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cleanupstage',
            name='type',
            field=models.CharField(choices=[('openstack', 'openstack'), ('ansible', 'ansible')], default='openstack', help_text='Type of the stage', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allocationstage',
            name='end',
            field=models.DateTimeField(default=None, help_text='Timestamp indicating when the stage execution ended.', null=True),
        ),
        migrations.AlterField(
            model_name='allocationstage',
            name='error_message',
            field=models.TextField(default=None, help_text='Error message describing the potential error.', null=True),
        ),
        migrations.AlterField(
            model_name='allocationstage',
            name='failed',
            field=models.BooleanField(default=False, help_text='Indicates whether the stage execution failed.'),
        ),
        migrations.AlterField(
            model_name='allocationstage',
            name='start',
            field=models.DateTimeField(default=None, help_text='Timestamp indicating when the stage execution started.', null=True),
        ),
        migrations.AlterField(
            model_name='cleanupstage',
            name='end',
            field=models.DateTimeField(default=None, help_text='Timestamp indicating when the stage execution ended.', null=True),
        ),
        migrations.AlterField(
            model_name='cleanupstage',
            name='error_message',
            field=models.TextField(default=None, help_text='Error message describing the potential error.', null=True),
        ),
        migrations.AlterField(
            model_name='cleanupstage',
            name='failed',
            field=models.BooleanField(default=False, help_text='Indicates whether the stage execution failed.'),
        ),
        migrations.AlterField(
            model_name='cleanupstage',
            name='start',
            field=models.DateTimeField(default=None, help_text='Timestamp indicating when the stage execution started.', null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='max_size',
            field=models.IntegerField(help_text='Maximum amount of Allocation Units associated with this pool.'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='private_management_key',
            field=models.TextField(help_text='Private key for management access.'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='public_management_key',
            field=models.TextField(help_text='Public key for management access.'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='rev',
            field=models.TextField(help_text='Definition revision used for sandboxes.'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='rev_sha',
            field=models.TextField(help_text='SHA of the Definition revision.'),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='private_user_key',
            field=models.TextField(help_text='Private key for user access.'),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='public_user_key',
            field=models.TextField(help_text='Public key for management access.'),
        ),
        migrations.AlterField(
            model_name='stackallocationstage',
            name='status',
            field=models.CharField(help_text='Stack status', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stackallocationstage',
            name='status_reason',
            field=models.TextField(help_text='Stack status reason', null=True),
        ),
    ]
