# Generated by Django 2.2.12 on 2020-05-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0005_auto_20200409_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='RQJob',
            fields=[
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rq_job', serialize=False, to='sandbox_instance_app.AllocationStage')),
                ('job_id', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
