# Generated by Django 2.2.12 on 2020-05-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0006_rqjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='id',
            field=models.PositiveIntegerField(default=-1024, primary_key=True, serialize=False),
        ),
    ]
