# Generated by Django 5.0.6 on 2024-07-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0011_alter_pool_send_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poollock',
            name='training_access_token',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
