# Generated by Django 2.2.26 on 2022-02-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0003_auto_20210920_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupTerraformOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('cleanup_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terraform_outputs', to='sandbox_instance_app.CleanupStage')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationTerraformOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('allocation_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terraform_outputs', to='sandbox_instance_app.AllocationStage')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='HeatStack',
            new_name='TerraformStack',
        ),
    ]
