# Generated by Django 2.2.28 on 2022-08-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0004_allocationterraformoutput_cleanupterraformoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='id',
            field=models.CharField(default='1', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
