# Generated by Django 2.2.28 on 2023-04-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sandbox_instance_app', '0006_sandboxlock_created_by_squashed_0008_auto_20230331_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandboxallocationunit',
            name='pool',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='allocation_units',
                to='sandbox_instance_app.Pool',
            ),
        ),
    ]
