# Generated by Django 2.2.28 on 2023-07-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0007_auto_20230426_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='size',
            field=models.PositiveIntegerField(default=0, help_text='Current amount of Allocation Units associated with this pool.'),
        ),
    ]
