# Generated by Django 5.0.6 on 2024-05-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0009_pool_comment_pool_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='send_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SandboxRequestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_count', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('failed_count', models.IntegerField(default=0)),
                ('finished_count', models.IntegerField(default=0)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sandbox_instance_app.pool')),
            ],
        ),
    ]
