# Generated by Django 5.0.6 on 2024-06-07 10:49

import django.db.models.deletion
import crczp.sandbox_instance_app.lib.email_notifications
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0010_pool_send_emails_sandboxrequestgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='send_emails',
            field=models.BooleanField(default=False, validators=[crczp.sandbox_instance_app.lib.email_notifications.validate_emails_enabled]),
        ),
        migrations.AlterField(
            model_name='sandboxrequestgroup',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox_instance_app.pool'),
        ),
    ]
