# Generated by Django 5.0.6 on 2024-08-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0012_poollock_training_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandbox',
            name='ready',
            field=models.BooleanField(default=False, help_text='Is the sandbox ready to use for trainings.'),
        ),
    ]
