# Generated by Django 2.2.19 on 2021-04-23 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0002_pool_management_certificate'),
        ('sandbox_ansible_app', '0002_auto_20200619_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerContainerCleanup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.TextField()),
                ('cleanup_stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sandbox_instance_app.CleanupStage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
