# Generated by Django 2.2.11 on 2020-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_definition_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='name',
            field=models.CharField(help_text='Name of the definition.', max_length=100),
        ),
        migrations.AlterField(
            model_name='definition',
            name='rev',
            field=models.TextField(default='master', help_text='Default revision.'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='url',
            field=models.TextField(help_text='URL of the definition.'),
        ),
    ]
