name: Sandbox service CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      confirm_action:
        description: "Type 'yes' if you want to create a new tag"
        required: true
        default: "no"

jobs:
  get_current_version:
    uses: cyberrangecz/actions-templates/.github/workflows/get_version.yml@master
    with:
      file_path: "pyproject.toml"

  codeQuality:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04
    env:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      TERM: xterm-256color
      FORCE_COLOR: "1"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.12"

      - name: install and run tox
        run: |
          uv tool install tox --with tox-uv
          tox

  build:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04
    needs: [get_current_version, codeQuality]
    env:
      VERSION: ${{ needs.get_current_version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          TAG: ${{ github.ref == 'refs/heads/master' && format('{0}', env.VERSION ) || format('{0}-dev', env.VERSION) }}
        uses: docker/build-push-action@v6
        with:
          context: .  # Path to the Dockerfile
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/sandbox-service:${{ env.TAG }}

  generate_docs:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.12"

      - name: Generate and Push Swagger Docs
        run: |
          cp config.yml-template ./config.yml
          mkdir output
          uv sync
          uv run python manage.py spectacular --file output/crczp-sandbox-service-swagger-open-api.yaml

      - name: Upload Docs files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  upload_docs:
    needs: generate_docs
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Controls if version consistent with semver and higner than last git tag.
  control_tag:
    if: github.event.pull_request.base.ref == 'master' || github.ref == 'refs/heads/master'
    needs: get_current_version
    uses: cyberrangecz/actions-templates/.github/workflows/tag_control_template.yml@master
    with:
      VERSION: ${{ needs.get_current_version.outputs.version }}

  # Push tag only from manual workflow_dispatch with confirmed tag creation
  push_tag:
    if: github.ref == 'refs/heads/master' && github.event.inputs.confirm_action == 'yes'
    needs: [get_current_version, control_tag, build]
    uses: cyberrangecz/actions-templates/.github/workflows/tag_push_template.yml@master
    with:
      VERSION: ${{ needs.get_current_version.outputs.version }}
